"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-7ib8&=5%p26a%vfa=l^t^@xx08k^x_2p24mk6rp3t@!f9w98*2'

DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app.apps.RelationshipAppConfig',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

AUTH_USER_MODEL = "bookshelf.CustomUser"

LOGIN_REDIRECT_URL = "book_list"
LOGOUT_REDIRECT_URL = "login"

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# =========================
# SECURITY SETTINGS (TASK)
# =========================

SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent browser from guessing content type
SECURE_BROWSER_XSS_FILTER = True    # Enable browser XSS filtering
X_FRAME_OPTIONS = "DENY"            # Prevent clickjacking

CSRF_COOKIE_SECURE = True           # Only send CSRF cookie over HTTPS
SESSION_COOKIE_SECURE = True        # Only send session cookie over HTTPS

SECURE_SSL_REDIRECT = True          # Force HTTPS (redirect HTTP -> HTTPS)

# HSTS settings
SECURE_HSTS_SECONDS = 31536000             # Enforce HTTPS for 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True      # Apply HSTS to all subdomains
SECURE_HSTS_PRELOAD = True                 # Allow domain to be preloaded in browsers


CSRF_TRUSTED_ORIGINS = [
    "https://localhost",
    "https://127.0.0.1",
]


# =========================
# CONTENT SECURITY POLICY (CSP)
# =========================

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "script-src": ("'self'",),
        "style-src": ("'self'",),
    }
}